Fixed possible UnicodeDecodeError in setup.py on Python 3.6.
Put the long description in setup.cfg, without replacing characters.
See this error on Plone Jenkins, https://jenkins.plone.org/job/plone-5.2-python-3.6/1058/console

```
Develop: '/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form'
Traceback (most recent call last):
  File "/tmp/tmps_fh_how", line 14, in <module>
    exec(compile(f.read(), '/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form/setup.py', 'exec'))
  File "/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form/setup.py", line 61, in <module>
    'util.txt',
  File "/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form/setup.py", line 46, in <listcomp>
    for name in ('README.txt',
  File "/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form/setup.py", line 22, in read
    text = f.read()
  File "/home/jenkins/shiningpanda/jobs/65a48de5/virtualenvs/d41d8cd9/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 752: ordinal not in range(128)
While:
  Installing.
  Processing develop directory '/home/jenkins/workspace/plone-5.2-python-3.6/src/z3c.form'.
```

I have seen it go wrong for more packages the last couple of months.
Locally I see no problem with Python 3.6, so it *could* be a problem only on one Jenkins node.
But if it happens there, it might happen for other users too.

See another package where I initially fixed it by hacking something in `setup.py`,
and then replaced it with `setup.cfg` in this commit:
https://github.com/plone/Products.CMFPlacefulWorkflow/commit/eda6670f50436d2dea426a389563df1223760978